name: Manual Production Deploy
run-name: 'Manual Production Deploy: ${{ github.event.inputs.version }}'
concurrency: Manual Production Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  deploy_to_production_start_slack:
    if: github.repository_owner == 'Informatievlaanderen'
    name: Deploy to production started
    environment: prd
    runs-on: ubuntu-latest

    steps:
    - name: Notify deployment started
      uses: slackapi/slack-github-action@v3
      with:
        method: chat.postMessage
        token: ${{ secrets.VBR_SLACK_BOT_TOKEN }}
        payload: |
          channel: '#team-dinosaur-dev'
          text: 'Deployment of basisregisters-grb to production has started'

  deploy_services_to_production:
    if: github.repository_owner == 'Informatievlaanderen'
    needs: [ deploy_to_production_start_slack ]
    name: Deploy services to Production
    uses: informatievlaanderen/build-pipeline/.github/workflows/deploy-v4.1.yml@main
    strategy:
      matrix:
        services: [
          'grb-api',
          'grb-processor-upload',
          'grb-processor-job'
        ]
    with:
      environment: 'prd'
      service-name: ${{ matrix.services }}
      application: ${{ matrix.services }}
      version: ${{ github.event.inputs.version }}
      domain: 'building'
      project: 'grawr'
      use-subfolder: true
    secrets: inherit

  deploy_to_production_finish_slack:
    if: github.repository_owner == 'Informatievlaanderen'
    needs: [ deploy_services_to_production ]
    name: Deploy to production finished
    runs-on: ubuntu-latest

    steps:
    - name: Notify deployment finished
      uses: slackapi/slack-github-action@v3
      with:
        method: chat.postMessage
        token: ${{ secrets.VBR_SLACK_BOT_TOKEN }}
        payload: |
          channel: '#team-dinosaur-dev'
          text: 'Deployment of basisregisters-grb to production has finished'
